name: Build and deploy .NET POC

on:
  push:
    branches:
      - main-net

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/neta-hiring-dotnet-api
  IMAGE_TAG: main-net

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Show files
        run: |
          pwd
          ls -la
          find . -maxdepth 4 -type f | sort

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./neta-hiring-poc/dotnet-api/NetaSystems.Hiring.Api
          file: ./neta-hiring-poc/dotnet-api/NetaSystems.Hiring.Api/NetaSystems.Hiring.Api/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Trigger Portainer webhook
        run: |
          curl -X POST "${{ secrets.PORTAINER_WEBHOOK_URL }}"